/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test.check" instead.
 */

#include <check.h>

#line 1 "test.check"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "s21_string.h"

START_TEST(memcpy_1)
{
#line 7
char buf1[50] = "It's check memcpy - ok", buf2[50];
ck_assert_str_eq(memcpy(buf2,buf1,21),s21_memcpy(buf2,buf1,21));

}
END_TEST

START_TEST(memcpy_2)
{
#line 11
char buf1[50] = "Hello world\0", buf2[50];
ck_assert_str_eq(memcpy(buf2,buf1,12),s21_memcpy(buf2,buf1,12));

}
END_TEST

START_TEST(memcpy_3)
{
#line 15
char buf1[50] = "Hello w\0orld", buf2[50];
ck_assert_str_eq(memcpy(buf2,buf1,10),s21_memcpy(buf2,buf1,10));

}
END_TEST

START_TEST(memcpy_4)
{
#line 19
char buf1[50] = "a\n\0", buf2[50];
ck_assert_str_eq(memcpy(buf2,buf1,3),s21_memcpy(buf2,buf1,3));

}
END_TEST

START_TEST(memcpy_5)
{
#line 23
char buf1[50] = "Hel\0lo w\0orld", buf2[50];
ck_assert_str_eq(memcpy(buf2,buf1,5),s21_memcpy(buf2,buf1,5));

}
END_TEST

START_TEST(memmove_1)
{
#line 27
char src[] = "Hello world\0";
char dest[] = "rembo";
ck_assert_str_eq(memmove(dest,src,2),s21_memmove(dest,src,2));

}
END_TEST

START_TEST(memmove_2)
{
#line 32
char src[] = "Hello world\0";
char dest[] = "a\n\0";
ck_assert_str_eq(memmove(dest,src,1),s21_memmove(dest,src,1));

}
END_TEST

START_TEST(memmove_3)
{
#line 37
char src[] = "Hel\0lo world\0";
char dest[] = "rembo wave sorry";
ck_assert_str_eq(memmove(dest,src,6),s21_memmove(dest,src,6));

}
END_TEST

START_TEST(memmove_4)
{
#line 42
char src[] = "Hel\nlo \0world\0";
char dest[] = "salam wave";
ck_assert_str_eq(memmove(dest,src,6),s21_memmove(dest,src,6));

}
END_TEST

START_TEST(memmove_5)
{
#line 47
char src[] = " \n\0";
char dest[] = "rembo hello";
ck_assert_str_eq(memmove(dest,src,1),s21_memmove(dest,src,1));

}
END_TEST

START_TEST(memset_1)
{
#line 52
char str[] = "salam aleikum memset!n";
ck_assert_str_eq(memset(str,'*',12),s21_memset(str,'*',12));

}
END_TEST

START_TEST(memset_2)
{
#line 56
char str[] = "Hello \0world\0";
ck_assert_str_eq(memset(str,'*',9),s21_memset(str,'*',9));

}
END_TEST

START_TEST(memset_3)
{
#line 60
char str[] = "Hell\no \0world\0";
ck_assert_str_eq(memset(str,'*',8),s21_memset(str,'*',8));

}
END_TEST

START_TEST(memset_4)
{
#line 64
char str[] = "a\n\0";
ck_assert_str_eq(memset(str,'*',2),s21_memset(str,'*',2));

}
END_TEST

START_TEST(memset_5)
{
#line 68
char str[] = "\n\0";
ck_assert_str_eq(memset(str,'*',2),s21_memset(str,'*',2));

}
END_TEST

START_TEST(strncpy_1)
{
#line 72
char src[40] = "This is interesting joke";
char dest[100];
ck_assert_str_eq(strncpy(dest,src,26),s21_strncpy(dest,src,26));

}
END_TEST

START_TEST(strncpy_2)
{
#line 77
char src[40] = "Hello world\n\0";
char dest[100];
ck_assert_str_eq(strncpy(dest,src,13),s21_strncpy(dest,src,13));

}
END_TEST

START_TEST(strncpy_3)
{
#line 82
char src[40] = "a\n\0";
char dest[100];
ck_assert_str_eq(strncpy(dest,src,2),s21_strncpy(dest,src,2));

}
END_TEST

START_TEST(strncpy_4)
{
#line 87
char src[40] = "Hello world\0";
char dest[100];
ck_assert_str_eq(strncpy(dest,src,12),s21_strncpy(dest,src,12));

}
END_TEST

START_TEST(strncpy_5)
{
#line 92
char src[40] = " \n\0";
char dest[100];
ck_assert_str_eq(strncpy(dest,src,2),s21_strncpy(dest,src,2));

}
END_TEST

START_TEST(strcpy_1)
{
#line 97
char src[] = "Hello world\0";
char dest[] = "abcdefghijklm";
ck_assert_str_eq(strcpy(dest, src),s21_strcpy(dest, src));

}
END_TEST

START_TEST(strcpy_2)
{
#line 102
char src[] = "Hello world\n\0";
char dest[] = "abcdefghijklm";
ck_assert_str_eq(strcpy(dest, src),s21_strcpy(dest, src));

}
END_TEST

START_TEST(strcpy_3)
{
#line 107
char src[] = "a\n\0";
char dest[] = "ab";
ck_assert_str_eq(strcpy(dest, src),s21_strcpy(dest, src));

}
END_TEST

START_TEST(strcpy_4)
{
#line 112
char src[] = " \0";
char dest[] = "ab";
ck_assert_str_eq(strcpy(dest, src),s21_strcpy(dest, src));

}
END_TEST

START_TEST(strcpy_5)
{
#line 117
char src[] = "hello\0 russian";
char dest[] = "abcdefghijklmnfff";
ck_assert_str_eq(strcpy(dest, src),s21_strcpy(dest, src));
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, memcpy_1);
    tcase_add_test(tc1_1, memcpy_2);
    tcase_add_test(tc1_1, memcpy_3);
    tcase_add_test(tc1_1, memcpy_4);
    tcase_add_test(tc1_1, memcpy_5);
    tcase_add_test(tc1_1, memmove_1);
    tcase_add_test(tc1_1, memmove_2);
    tcase_add_test(tc1_1, memmove_3);
    tcase_add_test(tc1_1, memmove_4);
    tcase_add_test(tc1_1, memmove_5);
    tcase_add_test(tc1_1, memset_1);
    tcase_add_test(tc1_1, memset_2);
    tcase_add_test(tc1_1, memset_3);
    tcase_add_test(tc1_1, memset_4);
    tcase_add_test(tc1_1, memset_5);
    tcase_add_test(tc1_1, strncpy_1);
    tcase_add_test(tc1_1, strncpy_2);
    tcase_add_test(tc1_1, strncpy_3);
    tcase_add_test(tc1_1, strncpy_4);
    tcase_add_test(tc1_1, strncpy_5);
    tcase_add_test(tc1_1, strcpy_1);
    tcase_add_test(tc1_1, strcpy_2);
    tcase_add_test(tc1_1, strcpy_3);
    tcase_add_test(tc1_1, strcpy_4);
    tcase_add_test(tc1_1, strcpy_5);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
